import Head from 'next/head'

export default function PageHead({ title }: { title: string }) {
  return (
    <Head>
      <title>SpaceX | {title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
